---
title: '<div class="jumbotron"><h1 class="title toc-ignore display-3">Version control with git</h1></div>'
author: "Danielle Navarro"
date: "30 November 2018"
output:
  html_document:
    includes:
      in_header: header.html
    theme: flatly
    highlight: textmate
    css: mystyle.css

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Installing git

The first thing we need to do is make sure you have a working version of git on your computer, which we'll be referring to as the *local* machine thoughout this tutorial. Installing git on your local machine is (hopefully) not too difficult. There are several different ways you can do it, but the simplest ones are listed below:

- For Windows users, go to https://gitforwindows.org/. When installing, make sure you select the "Use Git from the Windows Command Prompt" option. 
- For Mac users, you can install the "Xcode command line tools" from the App Store (you don't need all of Xcode), which comes with git

Once you've completed the installation, it's a good idea to check that everything worked. For Windows users, open the Windows Command Prompt and type `git --version`. When I do this on my machine this is what I get:

```{}
> git --version

git version 2.19.1.windows.1
```

For Mac users it's exactly the same except you open the Terminal. When I do this on my Mac it turns out I have a slightly dated version of git, and should probably update at some point:

```{}
> git --version 

git version 2.15.2 (Apple Git 101.1)
```

As long as you're getting a message that tells you that git exists then you're good to go.


## Introducing yourself to git

In a moment we'll get you to sign up for an account with GitHub, but while we're here at the command line, we might as well make a few settings. You can tell git who you are by using the `git config` command. For me, that means I do this:

```{}
git config --global user.name 'Danielle Navarro'
git config --global user.email 'd.navarro@unsw.edu.au'
```

Jenny Bryan has some [very good advice](http://happygitwithr.com/hello-git.html#more-about-git-config) about some important config settings you can play with. You can see more about what the various options are with this command:

```{}
git config --global --list
```


## Getting a GitHub account

The next step in the process is setting up an account with a service that hosts *remote* git repositories for you in the cloud. There are many different services, but we'll use GitHub for this. Go to the GitHub website at https://github.com/ and follow the sign up instructions. Some notes:

- Pick a sensible username, because there's a good chance it will follow you around for a long time. You can change your username, but bad things can happen.
- When you sign up for an account it *will* need to be associated with an email address. You should pick the address that makes sense for you (probably your university account)
- A nice feature if you have a university email address and are using GitHub for edication: youcan  apply for a "developer" account (which are normally $7/month) for free You can apply for it by following the instructions [here](https://help.github.com/articles/applying-for-an-academic-research-discount/). It can take a few days, though mine was approved in minutes. 
- **Important**: the email address that you use for GitHub needs to be the same one that you listed in the `git config` command earlier.

## Client or command line?

There are several differnt ways you can use git, but maybe the biggest distinction is between using the *command line* tools (typing commands in at the Windows Command Prompt or the Mac Terminal) and using a *git client* (software that has a nice graphical user interface). In the long run it's probably worthwhile exploring a few different git clients: 
as Jenny Bryan says, it will spare you the tediousness of ["command line bullshittery"](http://www.pgbovine.net/command-line-bullshittery.htm). [GitKraken](https://www.gitkraken.com/) is a fairly popular option, but RStudio now has a nice git client built in, so you might want to explore that.

That being said for our purposes we're going to use the command line. That's not because we want to be "hardcore" but because most git clients are built for people who already understand git, and so the user interface is designed to show you "everything at a glance", and (for me at least) the visual complexity of it is overhwleming. Because this is just a "getting started" tutorial we'll just stick to some simple commands.


## Our first workflow: Backing up your work to GitHub

The simplest way to use GitHub is to archive and backup everything

- Create the repository on GitHub (the *origin*)
- *Clone* a local copy to your computer
- Make changes
- Check the *status*
- Make a local *commit* 
- *Push* the commits back up to GitHub

Any time you accidentally set fire to your computer, you can just clone the repository from GitHub to another machine and keep working.


## Our second workflow

- Adding another contributor on GitHub
- Using `pull` and `push` to keep work in sync
- Using the GitHub issue tracker to work together


## Beyond this

Once you're comfortable, there's more cool things you can do. Suppose you want to try out a really cool idea, but maybe it won't  work; you can create a new *branch* of the repository, which lets you make whatever changes you want. If it doesn't work, you can switch back to the master branck. If it does, you can merge the new changes back in. You can zoom forward and backward in time, inspecting the repository at different stages of development. You can create your own *fork* of someone else's repository, and if you want them to make some changes you can make a *pull request* which asks them to incorporate your code into their work. These workflows are all very cool, and a lot of them can all be done without having to leave RStudio, but we won't cover those here. 

Instead I'll suggest that when you're ready, have a read through [Happy Git and GitHub for the useR](http://happygitwithr.com/) as a great resource to introduce you to these things.


## Getting started 

From the Windows command prompt:

```{}
> git init
Initialized empty Git repository in C:/Users/Dan/GitHub/myproject/.git/
```

From Mac OS terminal or Linux shell:

```{}
> git init
Initialized empty Git repository in /home/danielle/myproject/.git/
```


```{}
> git status

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        README.md
```


```{}
> git add --all
> git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   README.md
```


```{}
> git commit -m "my first commit"
[master (root-commit) adfa917] my first commit
 1 file changed, 3 insertions(+)
 create mode 100644 README.md
```




## Further resources

- [Happy Git with R](http://happygitwithr.com/) by Jenny Bryan and Jim Hester
-


